### ISSUE TITLE
[Website] Pending design fixes

### ISSUE THREAD

**Issue by melissawm** [acquire-project/acquire-docs#7]
A few design items still need to be implemented:

- [x] Zulip logo/link in top navbar - #14
- [x] GitHub, Zulip and PyPI logos/links in footer - #14
- [x] Footer styling and display of html elements (i.e. text alignment) - #14
- [x] Hover color (blue) for Prev/Next links - #15 
- [x] Dark mode?
- [ ] Domain name
- [x] Admonition styling - https://github.com/acquire-project/acquire-docs/pull/13
- [x] Syntax highlighting - #17
- [x] Mobile menu - #16
- [x] Link styling - #57
- [x] Logos in header/footer are inconsistent in different pages - #30, #50 

Feel free to edit this issue with more items as they show up.

**Comment by melissawm** [comment]
Do we want to re-think the domain name question (e.g. use something like acquire-imaging.org)? If not, I think we can close this issue.

**Comment by aliddell** [comment]
^ @nclack @chili-chiu

**Comment by dgmccart** [comment]
We will stick with the github.io domain name, so I am closing this issue as all the other items are completed.
